apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-kafka-controller-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: ebs-sc  # StorageClass를 명시적으로 지정