apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi  # 요청할 스토리지 크기
  storageClassName: ebs-sc  # 앞서 정의한 스토리지 클래스 이름
