apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  # 원하는 스토리지 크기로 조정
  storageClassName: ebs-sc  # 이전에 정의한 스토리지 클래스 이름